# Generated by Django 5.0.14 on 2025-12-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanartifact',
            name='kind',
            field=models.CharField(choices=[('raw_mesh', 'Raw Mesh'), ('processed_mesh', 'Processed Mesh'), ('floorplan', 'Floorplan'), ('floorplan_svg', 'Floorplan SVG'), ('camera_path', 'Camera Path'), ('screen_capture', 'Screen Capture'), ('metadata', 'Metadata'), ('roomplan_json', 'RoomPlan JSON')], max_length=32),
        ),
    ]
